export interface Report {
  id?: number;              // Optional because it's generated by MySQL
  title: string;
  description: string;
  category_id: number;      // Matches the Foreign Key in your DB
  category_name?: string;   // Useful when you JOIN the categories table
  type: 'Lost' | 'Found';   // Using a Union type for strictness
  location?: string;
  contact_info?: string;
  image_path?: string;
  status: 'Pending' | 'Approved' | 'Resolved';
  created_at?: Date;
}

export interface Category {
  id: number;
  name: string;
}
